//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply
    {
        public Apply()
        {
            this.HandleApplies = new HashSet<HandleApply>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int ApplyRole { get; set; }
        public int State { get; set; }
        public string LvXingSheZeRenXian { get; set; }
        public string RenShenYiWaiXian { get; set; }
        public string RongYuChengHao { get; set; }
        public string AjiLuXingShe { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<HandleApply> HandleApplies { get; set; }
    }
}
