//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpArticle
    {
        public int Id { get; set; }
        public int HelpTypeId { get; set; }
        public string Title { get; set; }
        public int Weight { get; set; }
        public string HelpContent { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual HelpType HelpType { get; set; }
    }
}
