//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuXianType
    {
        public LuXianType()
        {
            this.Product2Type = new HashSet<Product2Type>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
        public string TypeTag { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Weight { get; set; }
        public int IsDelete { get; set; }
    
        public virtual ICollection<Product2Type> Product2Type { get; set; }
    }
}
