//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int ToCompanyId { get; set; }
        public string MessageContent { get; set; }
        public int RelatedId { get; set; }
        public int State { get; set; }
        public int IsRead { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
