//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FenXiaoDBEntities : DbContext
    {
        public FenXiaoDBEntities()
            : base("name=FenXiaoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Apply> Applies { get; set; }
        public virtual DbSet<ChildProduct> ChildProducts { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<HandleApply> HandleApplies { get; set; }
        public virtual DbSet<HandleReturnForm> HandleReturnForms { get; set; }
        public virtual DbSet<HelpArticle> HelpArticles { get; set; }
        public virtual DbSet<HelpType> HelpTypes { get; set; }
        public virtual DbSet<LoginInfo> LoginInfoes { get; set; }
        public virtual DbSet<LuXianType> LuXianTypes { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<OrderForm> OrderForms { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<Pro2Page> Pro2Page { get; set; }
        public virtual DbSet<Product2Type> Product2Type { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ReturnForm> ReturnForms { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
    }
}
