//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product2Type
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int ProductId { get; set; }
    
        public virtual LuXianType LuXianType { get; set; }
        public virtual Product Product { get; set; }
    }
}
