//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FenXiao.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCompany
    {
        public int Id { get; set; }
        public string YingYeZhiZhao { get; set; }
        public string CompanyName { get; set; }
        public string YingYeZhiZhaoImg { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyPhone { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int State { get; set; }
        public string LianXiRen { get; set; }
        public string Phone { get; set; }
        public string ZuoJi { get; set; }
        public string JingYingXuKe { get; set; }
        public string FaRenShenFenZhengImg { get; set; }
        public int CompanyId { get; set; }
    }
}
